package com.campusos.portal.domain;

public enum Event {
    AUTO_VALIDATE, AUTO_CHECK, AUTO_ELIGIBILITY, AUTO_ASSIGN, APPLY, WRITE_RECORD,
    APPROVE, REJECT, VERIFY, RETURN, RESUBMIT, START_REVIEW, RESOLVE
}
