package com.campusos.portal.domain;

public enum SideEffect {
    VALIDATE_LEAVE,
    MUTATE_ATTENDANCE,
    CHECK_CERTIFICATE,
    WRITE_ACADEMIC_RECORD,
    GENERATE_VERIFICATION_ID,
    PUBLISH_CERT_TO_DOCUMENTS,
    RUN_ELIGIBILITY,
    GENERATE_DOCUMENT,
    NOTIFY,
    NOTIFY_REJECTION
}
